"""Stdlib modules needed by external numpy/torch/soundfile/demucs in the frozen exe."""

# Keep in sync with hiddenimports in stem_organizer_py6.spec (imports this list).
_ML_STDLIB_MODULES = (
    'platform',
    'sysconfig',
    'timeit',
    'ctypes.util',
    'gzip',
    'logging.config',
    'mmap',
    'multiprocessing',
    'multiprocessing.spawn',
    'pickle',
    'socket',
    'ssl',
    'struct',
    'zipfile',
    'inspect',
    'copy',
    'functools',
    'itertools',
    'operator',
    'collections',
    'collections.abc',
    'typing',
    'enum',
    'traceback',
    'warnings',
    'contextlib',
    'threading',
    'types',
    'importlib.metadata',
    'importlib.resources',
    'importlib.machinery',
    'importlib.util',
    'hashlib',
    'hmac',
    'random',
    'tempfile',
    'glob',
    'fnmatch',
    'stat',
    'linecache',
    'dis',
    'ast',
    'abc',
    'io',
    'codecs',
    'tokenize',
    'keyword',
    'dataclasses',
    'weakref',
    'numbers',
    'decimal',
    'fractions',
    'textwrap',
    'string',
    're',
    'json',
    'base64',
    'binascii',
    'uuid',
    'queue',
    'signal',
    'subprocess',
    'locale',
    'gettext',
)


def ensure_stdlib_for_external_ml() -> None:
    for name in _ML_STDLIB_MODULES:
        try:
            __import__(name)
        except ImportError:
            pass
